config/routes.rb
Letsrateapp::Application.routes.draw do
  root :to => "home#index"

  resources :cars  
  devise_for :users

  match '/rate' => 'rater#create', :as => 'rate'
  match '/main' => 'home#main', :as => 'login_success'

end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :brand, :model, :title
  letsrate_rateable "performance", "price", "beauty"

  def to_s
  	[brand, model].compact.join(', ')
  end



end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  
  attr_accessible :rate, :dimension
  
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  letsrate_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  private
  def after_sign_in_path_for(resource)
  	login_success_path
  end
  def after_sign_out_path_for(resource)
  	root_path
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authenticate_user!, :only => :index
	def index		
	end

	def main
		@cars = Car.paginate(:page => params[:page])
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController 
  
  def create                                  
    if current_user.present?
      obj = eval "#{params[:klass]}.find(#{params[:id]})"     
      if params[:dimension].present?
        obj.rate params[:score].to_i, current_user.id, "#{params[:dimension]}"       
      else
        obj.rate params[:score].to_i, current_user.id 
      end
      
      render :json => true 
    else
      render :json => false        
    end
  end                                        
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_car.html.erb
<div class="car" style="border:1px solid #ececec; margin-bottom:4px; padding:4px;">
	<strong><%= link_to car, car_path(car) %></strong>
	<br />
	<i><%= car.title %></i>
	<br /><br />
	Performance <%= rating_for car, "performance" %>
	Price <%= rating_for car, "price" %>
	Beauty <%= rating_for car, "beauty" %>	
</div>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Brand</th>
    <th>Model</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.brand %></td>
    <td><%= car.model %></td>
    <td><%= car.title %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Brand:</b>
  <%= @car.brand %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>

<p>
  <b>Title:</b>
  <%= @car.title %>
</p>

<p>
	Performance : <%= rating_for @car, "performance" %>
</p>

<p>
	Price : <%= rating_for @car, "price" %>
</p>

<p>
	Beauty : <%= rating_for @car, "beauty" %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/home/index.html.erb
<h3>You must be logged in to rate something !</h3>

<%= link_to "Login", new_user_session_path %>

app/views/home/main.html.erb
<%= link_to "Add new car", new_car_path %>
<hr />
<%= render @cars %>
<%= will_paginate @cars %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Letsrateapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="messages">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	</div>
	<% if current_user %>
	<div class="authentication">
		<%= link_to "Logout", destroy_user_session_path, :method => :delete %>
	</div>
	<% end %>
	<hr />
	<%= yield %>
</body>
</html>